databases:
  - name: budgetappgeorgeh7
    databaseName: budgetappgeorgeh7
    user: budget_xdon_user
    plan: free

services:
  - type: web
    name: Budgetto
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetappgeorgeh7
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default